# yaml-language-server: $schema=../../../../../representations/runtime/json-schema/v1/deployment-spec.json
environment: demo
infraProfile: ecommerce-demo
services:
  - dataProductName: market-announcements
    environment: demo
    output: adls
  - dataProductName: income-statements
    environment: demo
    output: adls
  - dataProductName: stock-history
    environment: demo
    output: adls
  - dataProductName: financial-statements
    environment: demo
    output: adls
  - dataProductName: company-dividends
    environment: demo
    output: adls
  - dataProductName: public-disclosures
    environment: demo
    output: adls
  # - driver: nxd:pinecone:0.1.0
  #   environment: demo
  #   infraService: nxd-pinecone
  #   name: nxd-pinecone
  - driver: nxd:adls:2.0.0
    environment: demo
    infraService: adls
    name: adls
  - driver: nxd:kubernetes/rpc:1.0.0
    environment: demo
    infraService: mcp-api-service-k8s
    name: mcp-api-service-k8s
  - driver: nxd:databricks:1.0.0
    environment: demo
    infraService: nxd-databricks-storage
    name: nxd-databricks-storage
  - driver: nxd:databricks:1.0.0
    environment: demo
    infraService: nxd-databricks
    name: nxd-databricks
  - name: mock-access-control-service
    infraService: mock-access-control-service
    environment: demo
    driver: nxd-test:mock-universal:2.0.0
  - name: servicenow-sp-approval
    infraService: servicenow-sp-approval
    environment: demo
    driver: nxd:servicenow:1.0.0
